---
title: "Measure Theory"
author: "Ishaan Shrivastava"
date: "2025-01-30"
---

# $\sigma$-Algebra
A sigma algebra $\mathcal{A}$ on a set $X$ is a nonempty set of subsets of $X$ that is closed under complement, countable union, and countable intersection. In other words:
	$$\begin{aligned} &\mathcal{A} \subseteq \mathcal{P}(X) \text{ is a } \sigma\text{-algebra on }X\text{ if:} \\ (a) \text{ } &\phi, X \in \mathcal{A}& \\ (b) \text{ } & A \in \mathcal{A} \implies A^c \coloneqq X \setminus A \in \mathcal{A} \\ (c) \text{ } & A_i \in \mathcal{A}, i \in \mathbb{N} \implies \bigcup^\infty_{i=1} A_i \in \mathcal{A}\end{aligned}$$
$A \in \mathcal{A}$ is also called a $\mathcal{A}$-measurable set. In other words, a measure (which is a kind of generalised notion of volume) can be assigned to a $\sigma$-algebra. This notion is formally established later in [Measure](#measure)

### Borel $\sigma$-Algebra
For every $\mathcal{M} \subseteq \mathcal{P}(X)$, there is a smallest $\sigma$-algebra that contains $\mathcal{M}$:
$$\sigma(\mathcal{M})\coloneqq \bigcap_{\begin{aligned} &\mathcal{A}\supseteq \mathcal{M} \\ &\mathcal{A} \text{ } \sigma \text{-algebras} \end{aligned}} \mathcal{A} \space \space \leftarrow \sigma\text{-algebra generated by }\mathcal{M}$$
Note that uncountable unions of $\sigma$-algebras ($\mathcal{A}_i \subseteq \mathcal{P}(X), i \in \text{index set (uncountable)}$) are again valid $\sigma$-algebras. Easily provable using the original $\sigma$-algebra definition.

A Borel $\sigma$-algebra on a topological space $(X, \tau)$ (noted as $\mathcal{B}(X)$) is the $\sigma$-algebra generated by the open sets $\tau$. In other words:
$$\mathcal{B}(X)\coloneqq \sigma(\tau)$$
These Borel $\sigma$-algebras have some interesting properties that allow us to define a measure, or a generalised notion of volume, upon them, which we will later find is impossible to do on the entire powerset $\mathcal{P}(X)$

### Measure
Let us say that $(X, \mathcal{A})$ is a measurable space.
	$$\begin{aligned} &\text{A map } \mu \colon \mathcal{A} \rightarrow [0, \infty) \cup\{\infty\} \text{ is called a measure if:} \\ (a) \space & \mu(\phi) =  0\\ (b) \space & \mu\biggl(\bigcup_{i=1}^n A_i \biggr) =  \sum_{i=1}^{n}\sigma(A_i), \space\space\space\space\space\space\space\space \text{with }A_i \cap A_j = \phi, i \neq j \text{ }\forall \text{ countable sequences } A_i \in \mathcal{A}\end{aligned}$$
Collectively, $(X, \mathcal{A}, \mu)$ are referred to as a *measure space*.
