---
title: "Rotating Emphasis Manipulation"
author: "Ishaan Shrivastava"
date: "2026-05-24T20:07:43+05:30"
date-modified: "2026-05-24T20:07:43+05:30"
---

Reference - [https://www.sciencedirect.com/science/article/abs/pii/0001691889900073?via%3Dihub](Daniel Gopher, 1989 - Practice under changing priorities: An approach to the training of complex skills)

# Why
The core of **expert performance** is an <u>organised set of response strategies</u> than can be employed flexibly to meet task demands.

Subjects trained under <u>rotating emphasis manipulation</u> performed significantly better than control players, and experienced a **continued advantage increase after experiment** termination.

# What
The schema model of executive function observes the formation of **schemas**, individual and indivisible units of control that can be composed together (many, and often multiple at the same time together) in order to meet the demands of a complex task.

When performing a complicated task, human subjects often have little knowledge of, and do not spontaneously **explore, alternative strategies**. When led to do so, performance improves.

Performance under high-attention load conditions benefits most when subjects are trained on **several, varying levels of subelement priorities.**

# How
Divide skills into core components, train individually, together and then experiments with their composition. This is aptly called **[Part-Whole training](../part-whole-training/)**.

However, instead of training individual schemas in isolation of each other and in absence of the entire goal, only attempt to manipulate and assign the **relative emphasis (priority)** of selected subcomponents in a rotating manner.
